# ==================== locations/default.yaml ====================
# conf/locations/default.yaml

cities:
  - "المدينة"
  - "مكة"
  - "البصرة"
  - "الكوفة"
  - "بغداد"
  - "دمشق"
  - "القاهرة"
  - "الفسطاط"
  - "واسط"
  - "الري"
  - "نيسابور"
  - "هراة"
  - "الأندلس"
  - "قرطبة"
  - "إشبيلية"
  - "طليطلة"
  - "فاس"
  - "تونس"