# ==================== titles/default.yaml ====================
# conf/titles/default.yaml

prophet_titles:
  - "النبي"
  - "نبيه"
  - "رسول الله"
  - "الرسول"
  - "خاتم النبيين"
  - "سيد المرسلين"
  - "الرسول الكريم"
  - "النبي الكريم"
  - "المصطفى"
  - "خير البشر"

allah_references:
  - "الله"
  - "اللهم"
  - "سبحانه وتعالى"
  - "عز وجل"
  - "تبارك وتعالى"
  - "جل جلاله"
  - "سبحانه"
  - "المولى عز وجل"
  - "رب العالمين"
  - "الرحمن الرحيم"

special_titles:
  - "النبي صلى الله عليه وسلم"
  - "نبيه صلى الله عليه وسلم"
  - "رسول الله صلى الله عليه وسلم"
  - "الخليفة الراشد"
  - "أمير المؤمنين"
  - "رضي الله عن الصحابة أجمعين"
  - "الأئمة الأربعة"
  - "أهل البيت عليهم السلام"