# ==================== names/default.yaml ====================
# conf/names/default.yaml

common_names:
  - "محمد"
  - "أحمد"
  - "علي"
  - "حسن"
  - "حسين"
  - "عمر"
  - "عثمان"
  - "أبو"
  - "عبد"
  - "عبدالله"
  - "عبدالرحمن"
  - "إبراهيم"
  - "يوسف"
  - "موسى"
  - "عيسى"
  - "داود"
  - "سليمان"
  - "إسماعيل"
  - "إسحاق"
  - "يعقوب"