# config/arabic_ner.yaml

before_honorifics:
  - الشيخ
  - الإمام
  - الحافظ
  - القاضي
  - السيد
  - العلامة
  - الفقيه
  - المحدث
  - المجتهد
  - المفسر
  - الولي
  - المقرئ

after_honorifics:
  - صلى الله عليه وسلم
  - عليه السلام
  - ﷺ
  - رضي الله عنه
  - رضي الله عنها
  - رضي الله عنهم
  - رحمه الله
  - رحمها الله
  - رحمهم الله
  - رحمة الله عليه
  - رحمة الله عليها
  - أجزل الله مثوبته
  - تقبله الله
  - غفر الله له
  - عفا الله عنه
  - تغمده الله برحمته

prophet_titles:
  - النبي
  - نبيه
  - رسول الله
  - الرسول
  - خاتم النبيين
  - سيد المرسلين
  - الرسول الكريم
  - النبي الكريم

prophet_honorifics:
  - صلى الله عليه وسلم
  - عليه الصلاة والسلام
  - ﷺ
  - عليه السلام
  - صلى الله عليه وآله وسلم
  - صلى الله عليه وسلم وآله
  - صلى الله عليه وسلم وصحبه
  - صلى الله عليه وسلم وصحابته
  - صلى الله عليه وسلم وآله وصحبه
  - صلى الله عليه وسلم وآله وصحابته
  - صلى الله عليه وسلم وآله وصحابته أجمعين
  - صلى الله عليه وسلم وآله وصحابته الكرام
  - صلى الله عليه وسلم وآله وصحابته الغر الميامين
  - صلى الله عليه وسلم وآله وصحابته الطيبين الطاهرين

companion_honorifics:
  - رضي الله عنه
  - رضي الله عنها
  - رضي الله عنهم
  - رضي الله عنهما
  - رضوان الله عليه
  - رضوان الله عليها

scholar_honorifics:
  - رحمه الله
  - رحمها الله
  - رحمهم الله
  - رحمة الله عليه
  - رحمة الله عليها
  - أجزل الله مثوبته
  - تغمده الله برحمته
  - عفا الله عنه
  - غفر الله له
  - تقبل الله منه
  - تقبل الله منها
  - تقبل الله منهم
  - تقبل الله منا ومنكم
  - تقبل الله عمله
  - تقبل الله عملها
  - تقبل الله أعمالهم

allah_references:
  - الله
  - اللهم
  - سبحانه وتعالى
  - عز وجل
  - تبارك وتعالى
  - جل جلاله
  - سبحانه
  - المولى عز وجل

cities:
  - المدينة
  - مكة
  - البصرة
  - الكوفة
  - بغداد
  - دمشق
  - القاهرة
  - الفسطاط
  - واسط
  - الري
  - نيسابور
  - هراة
  - القدس
  - بيت المقدس
  - القدس الشريف
  - المدينة المنورة
  - مكة المكرمة
  - المدينة المنورة
  - مكة المكرمة 
  - الشام
  - بلاد الشام
  - العراق
  - بلاد الرافدين
  - مصر
  - دمشق 
  - اليمن
  - خراسان
  - الأندلس
  - المغرب
  - ماوراء النهر


common_names:
  - محمد
  - أحمد
  - علي
  - حسن
  - حسين
  - عمر
  - عثمان
  - أبو
  - عبد
  - عبدالله
  - عبدالرحمن
  - إبراهيم
  - يوسف

special_titles:
  - النبي صلى الله عليه وسلم
  - نبيه صلى الله عليه وسلم
  - رسول الله صلى الله عليه وسلم
  - الخليفة الراشد
  - أمير المؤمنين
  - رضي الله عن الصحابة أجمعين
