authenticity:
  sahih:
    score: 5
    keywords: ["صحيح", "authentic", "موثق"]
  hasan:
    score: 4
    keywords: ["حسن", "good"]
  daif:
    score: 2
    keywords: ["ضعيف", "weak"]

isnaad_status:
  muttasil:
    score: 5
    keywords: ["متصل", "connected"]
  munqati:
    score: 1
    keywords: ["منقطع", "broken"]

maten_defects:
  munkar:
    score: 1
    keywords: ["منكر", "rejected"]

