defaults:
  - _self_

# Your configuration parameters
model:
  name: "TurathLLM"
  version: "0.1.0"

data:
  input_dir: "data/raw"
  output_dir: "data/processed"

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 10